"""mmg rates now set to 1.65 pence per sms

Revision ID: 0040_adjust_mmg_provider_rate
Revises: 0039_fix_notifications
Create Date: 2016-07-06 15:19:23.124212

"""

# revision identifiers, used by Alembic.
revision = '0040_adjust_mmg_provider_rate'
down_revision = '0039_fix_notifications'

import uuid
from datetime import datetime

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    sql = (
        "INSERT INTO provider_rates (id, valid_from, rate, provider_id) "
        f"VALUES ('{uuid.uuid4()}', '{datetime(2016, 7, 1)}', 1.65, (SELECT id FROM provider_details WHERE identifier = 'mmg'))" 
    )
    print(sql)

    conn.execute(sa.text(sql))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    sql = "DELETE FROM provider_rates WHERE provider_id = (SELECT id FROM provider_details WHERE identifier = 'mmg') AND rate = 1.65"
    conn.execute(sa.text(sql))
    ### end Alembic commands ###

