"""

Revision ID: 0346_additional_table_changes
Revises: 0345_alter_VAProfileLocalCache
Create Date: 2022-05-26 21:59:00.256016

"""
from alembic import op
import sqlalchemy as sa


revision = '0346_additional_table_changes'
down_revision = '0345_alter_VAProfileLocalCache'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'complaints', 'notification_history', ['notification_id'], ['id'])
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'templates_history', 'provider_details', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'templates_history', 'communication_items', ['communication_item_id'], ['id'])
    op.drop_constraint('users_identity_provider_user_id', 'users', type_='unique')
    op.create_unique_constraint('uix_veteran_id', 'va_profile_local_cache', ['va_profile_id', 'communication_item_id', 'communication_channel_id'])
    op.drop_column('va_profile_local_cache', 'mpi_icn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_profile_local_cache', sa.Column('mpi_icn', sa.VARCHAR(length=29), autoincrement=False, nullable=False))
    op.drop_constraint('uix_veteran_id', 'va_profile_local_cache', type_='unique')
    op.create_unique_constraint('users_identity_provider_user_id', 'users', ['identity_provider_user_id'])
    op.drop_constraint(None, 'templates_history', type_='foreignkey')
    op.drop_constraint(None, 'templates_history', type_='foreignkey')
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    # ### end Alembic commands ###
