"""

Revision ID: 0347_create_stored_function
Revises: 0346_additional_table_changes
Create Date: 2022-05-26 22:02:40.859659

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

revision = '0347_create_stored_function'
down_revision = '0346_additional_table_changes'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_va_profile_opt_in_out = PGFunction(
        schema="public",
        signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed Boolean, _source_datetime timestamp)",
        definition='RETURNS boolean\nLANGUAGE sql AS $$\nINSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime, allowed)\n    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime, _allowed)\n\tON CONFLICT ON CONSTRAINT uix_veteran_id DO UPDATE\n    SET allowed = _allowed, source_datetime = _source_datetime\n    WHERE _source_datetime > va_profile_local_cache.source_datetime\n        AND va_profile_local_cache.va_profile_id = _va_profile_id\n        AND va_profile_local_cache.communication_item_id = _communication_item_id\n        AND va_profile_local_cache.communication_channel_id = _communication_channel_id\n    RETURNING true\n$$'
    )
    op.create_entity(public_va_profile_opt_in_out)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_va_profile_opt_in_out = PGFunction(
        schema="public",
        signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed Boolean, _source_datetime timestamp)",
        definition='RETURNS boolean\nLANGUAGE sql AS $$\nINSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime, allowed)\n    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime, _allowed)\n\tON CONFLICT ON CONSTRAINT uix_veteran_id DO UPDATE\n    SET allowed = _allowed, source_datetime = _source_datetime\n    WHERE _source_datetime > va_profile_local_cache.source_datetime\n        AND va_profile_local_cache.va_profile_id = _va_profile_id\n        AND va_profile_local_cache.communication_item_id = _communication_item_id\n        AND va_profile_local_cache.communication_channel_id = _communication_channel_id\n    RETURNING true\n$$'
    )
    op.drop_entity(public_va_profile_opt_in_out)

    # ### end Alembic commands ###
