"""

Revision ID: 11414710f61a
Revises: 0351_user_service_roles
Create Date: 2022-11-02 19:54:18.568514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0352_default_value_added_to_updated_at'
down_revision = '0351_user_service_roles'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_inbound_api_service_id', table_name='service_inbound_api')
    op.drop_index('ix_service_inbound_api_updated_by_id', table_name='service_inbound_api')
    op.drop_table('service_inbound_api')
    op.alter_column('communication_items', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(None, 'complaints', 'notification_history', ['notification_id'], ['id'])
    op.alter_column('dm_datetime', 'month_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'week_day_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'quartal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_quartal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_month',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_calendar_week',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_fido2_sessions_user_id'), 'fido2_sessions', ['user_id'], unique=True)
    op.create_index(op.f('ix_inbound_numbers_service_id'), 'inbound_numbers', ['service_id'], unique=False)
    op.alter_column('notification_history', 'notification_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notification_history', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notification_history', 'rate_multiplier',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('notifications', 'notification_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'rate_multiplier',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_notifications_service_created_at', table_name='notifications')
    op.alter_column('provider_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('provider_details_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('rates', 'rate',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('service_callback', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_service_callback_api_service_id', table_name='service_callback')
    op.drop_index('ix_service_callback_api_updated_by_id', table_name='service_callback')
    op.create_index(op.f('ix_service_callback_service_id'), 'service_callback', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_callback_updated_by_id'), 'service_callback', ['updated_by_id'], unique=False)
    op.create_unique_constraint('uix_service_callback_channel', 'service_callback', ['service_id', 'callback_channel'])
    op.alter_column('service_callback_history', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_service_callback_api_history_service_id', table_name='service_callback_history')
    op.drop_index('ix_service_callback_api_history_updated_by_id', table_name='service_callback_history')
    op.create_index(op.f('ix_service_callback_history_service_id'), 'service_callback_history', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_callback_history_updated_by_id'), 'service_callback_history', ['updated_by_id'], unique=False)
    op.alter_column('services', 'sending_domain',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('services', 'smtp_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('services_history', 'sending_domain',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('services_history', 'smtp_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'templates_history', 'communication_items', ['communication_item_id'], ['id'])
    op.create_foreign_key(None, 'templates_history', 'provider_details', ['provider_id'], ['id'])
    op.alter_column('user_to_service', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user_to_service', 'service_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('users_identity_provider_user_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_identity_provider_user_id'), 'users', ['identity_provider_user_id'], unique=True)
    op.alter_column('va_profile_local_cache', 'source_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('va_profile_local_cache', 'source_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_users_identity_provider_user_id'), table_name='users')
    op.create_unique_constraint('users_identity_provider_user_id', 'users', ['identity_provider_user_id'])
    op.alter_column('user_to_service', 'service_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user_to_service', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint(None, 'templates_history', type_='foreignkey')
    op.drop_constraint(None, 'templates_history', type_='foreignkey')
    op.alter_column('services_history', 'smtp_user',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services_history', 'sending_domain',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('services', 'smtp_user',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services', 'sending_domain',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_service_callback_history_updated_by_id'), table_name='service_callback_history')
    op.drop_index(op.f('ix_service_callback_history_service_id'), table_name='service_callback_history')
    op.create_index('ix_service_callback_api_history_updated_by_id', 'service_callback_history', ['updated_by_id'], unique=False)
    op.create_index('ix_service_callback_api_history_service_id', 'service_callback_history', ['service_id'], unique=False)
    op.alter_column('service_callback_history', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uix_service_callback_channel', 'service_callback', type_='unique')
    op.drop_index(op.f('ix_service_callback_updated_by_id'), table_name='service_callback')
    op.drop_index(op.f('ix_service_callback_service_id'), table_name='service_callback')
    op.create_index('ix_service_callback_api_updated_by_id', 'service_callback', ['updated_by_id'], unique=False)
    op.create_index('ix_service_callback_api_service_id', 'service_callback', ['service_id'], unique=False)
    op.alter_column('service_callback', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rates', 'rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_details_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('provider_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_notifications_service_created_at', 'notifications', ['service_id', 'created_at'], unique=False)
    op.alter_column('notifications', 'rate_multiplier',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('notifications', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'notification_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notification_history', 'rate_multiplier',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('notification_history', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_history', 'notification_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inbound_numbers_service_id'), table_name='inbound_numbers')
    op.drop_index(op.f('ix_fido2_sessions_user_id'), table_name='fido2_sessions')
    op.alter_column('dm_datetime', 'year_calendar_week',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_month',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_quartal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'quartal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'week_day_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'month_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.alter_column('communication_items', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('service_inbound_api',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bearer_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='service_inbound_api_service_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='service_inbound_api_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_inbound_api_pkey')
    )
    op.create_index('ix_service_inbound_api_updated_by_id', 'service_inbound_api', ['updated_by_id'], unique=False)
    op.create_index('ix_service_inbound_api_service_id', 'service_inbound_api', ['service_id'], unique=False)
    # ### end Alembic commands ###
