"""

Revision ID: 0353_missing_revision
Revises: 0352_updated_at_default
Create Date: 2022-12-12 22:29:53.057988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0353_missing_revision'
down_revision = '0352_updated_at_default'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_callback', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uix_service_callback_channel', 'service_callback', ['service_id', 'callback_channel'])
    op.alter_column('service_callback_history', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_to_service', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user_to_service', 'service_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_to_service', 'service_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user_to_service', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('service_callback_history', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uix_service_callback_channel', 'service_callback', type_='unique')
    op.alter_column('service_callback', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
