"""

Revision ID: 73ba076d31a5
Revises: 0369_va_profile_cache_fields
Create Date: 2024-08-05 13:51:38.281958

"""
from alembic import op
import sqlalchemy as sa

revision = '73ba076d31a5'
down_revision = '0369_va_profile_cache_fields'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('va_profile_local_cache', 'participant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('va_profile_local_cache', 'participant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
