"""

Revision ID: 73ba076d31a5
Revises: 0369_va_profile_cache_fields
Create Date: 2024-08-05 13:51:38.281958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '73ba076d31a5'
down_revision = '0369_va_profile_cache_fields'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'complaints', 'notification_history', ['notification_id'], ['id'])
    op.alter_column('dm_datetime', 'month_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'week_day_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'quartal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_quartal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_month',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_calendar_week',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_fido2_sessions_user_id'), 'fido2_sessions', ['user_id'], unique=True)
    op.alter_column('notification_failures', 'body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('notification_history', 'notification_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notification_history', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notification_history', 'rate_multiplier',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('notifications', 'notification_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'rate_multiplier',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_notifications_service_created_at', table_name='notifications')
    op.create_index(op.f('ix_promoted_templates_id'), 'promoted_templates', ['id'], unique=False)
    op.drop_column('promoted_templates', 'promoted_at')
    op.alter_column('rates', 'rate',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('reply_to_inbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_callback', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_service_callback_api_service_id', table_name='service_callback')
    op.drop_index('ix_service_callback_api_updated_by_id', table_name='service_callback')
    op.create_index(op.f('ix_service_callback_service_id'), 'service_callback', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_callback_updated_by_id'), 'service_callback', ['updated_by_id'], unique=False)
    op.create_unique_constraint('uix_service_callback_channel', 'service_callback', ['service_id', 'callback_channel'])
    op.alter_column('service_callback_history', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_service_callback_api_history_service_id', table_name='service_callback_history')
    op.drop_index('ix_service_callback_api_history_updated_by_id', table_name='service_callback_history')
    op.create_index(op.f('ix_service_callback_history_service_id'), 'service_callback_history', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_callback_history_updated_by_id'), 'service_callback_history', ['updated_by_id'], unique=False)
    op.alter_column('services', 'sending_domain',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('services', 'smtp_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('services_history', 'sending_domain',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('services_history', 'smtp_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('sessions', 'data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('index_sessions_on_session_id', table_name='sessions')
    op.drop_index('index_sessions_on_updated_at', table_name='sessions')
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessions_updated_at'), 'sessions', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'templates_history', 'communication_items', ['communication_item_id'], ['id'])
    op.create_foreign_key(None, 'templates_history', 'provider_details', ['provider_id'], ['id'])
    op.alter_column('user_to_service', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user_to_service', 'service_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('users_identity_provider_user_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_identity_provider_user_id'), 'users', ['identity_provider_user_id'], unique=True)
    op.alter_column('va_profile_local_cache', 'source_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('va_profile_local_cache', 'participant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('va_profile_local_cache', 'participant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('va_profile_local_cache', 'source_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_users_identity_provider_user_id'), table_name='users')
    op.create_unique_constraint('users_identity_provider_user_id', 'users', ['identity_provider_user_id'])
    op.alter_column('user_to_service', 'service_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user_to_service', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint(None, 'templates_history', type_='foreignkey')
    op.drop_constraint(None, 'templates_history', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_updated_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.create_index('index_sessions_on_updated_at', 'sessions', ['updated_at'], unique=False)
    op.create_index('index_sessions_on_session_id', 'sessions', ['session_id'], unique=True)
    op.alter_column('sessions', 'data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('services_history', 'smtp_user',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services_history', 'sending_domain',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services_history', 'prefix_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('services', 'smtp_user',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services', 'sending_domain',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_service_callback_history_updated_by_id'), table_name='service_callback_history')
    op.drop_index(op.f('ix_service_callback_history_service_id'), table_name='service_callback_history')
    op.create_index('ix_service_callback_api_history_updated_by_id', 'service_callback_history', ['updated_by_id'], unique=False)
    op.create_index('ix_service_callback_api_history_service_id', 'service_callback_history', ['service_id'], unique=False)
    op.alter_column('service_callback_history', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uix_service_callback_channel', 'service_callback', type_='unique')
    op.drop_index(op.f('ix_service_callback_updated_by_id'), table_name='service_callback')
    op.drop_index(op.f('ix_service_callback_service_id'), table_name='service_callback')
    op.create_index('ix_service_callback_api_updated_by_id', 'service_callback', ['updated_by_id'], unique=False)
    op.create_index('ix_service_callback_api_service_id', 'service_callback', ['service_id'], unique=False)
    op.alter_column('service_callback', 'bearer_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reply_to_inbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rates', 'rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('promoted_templates', sa.Column('promoted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_promoted_templates_id'), table_name='promoted_templates')
    op.create_index('ix_notifications_service_created_at', 'notifications', ['service_id', 'created_at'], unique=False)
    op.alter_column('notifications', 'rate_multiplier',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('notifications', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'notification_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notification_history', 'rate_multiplier',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('notification_history', 'international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_history', 'notification_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notification_failures', 'body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_fido2_sessions_user_id'), table_name='fido2_sessions')
    op.alter_column('dm_datetime', 'year_calendar_week',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_month',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'year_quartal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'quartal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'week_day_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dm_datetime', 'month_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    # ### end Alembic commands ###
