"""

Revision ID: 0378_sms_sender_length
Revises: 0377_template_content
Create Date: 2025-04-15 15:38:15.787278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0378_sms_sender_length'
down_revision = '0377_template_content'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_sms_senders', 'sms_sender',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_sms_senders', 'sms_sender',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
