version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: &vanotify_dockerfile ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools,test
    image: &vanotify_image notification_api
    volumes: &vanotify_volumes
      - "../:/app:rw"
    ports: &vanotify_ports
      - 6011:6011
    env_file: &vanotify_env_file
      - .local.env
    depends_on:
      - migrations
    command: ./scripts/run_app.sh
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

  migrations:
    build:
      context: ..
    image: *vanotify_image
    env_file: *vanotify_env_file
    volumes: *vanotify_volumes
    command: ["bash", "-c", "flask db upgrade"]


  celery:
    image: *vanotify_image
    volumes: *vanotify_volumes
    env_file: *vanotify_env_file
    command: >
      sh -c "/app/scripts/wait_for_it.sh localstack:4566 --timeout=30 -- /app/scripts/run_celery.sh"
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

  beat:
    image: *vanotify_image
    volumes: *vanotify_volumes
    env_file: *vanotify_env_file
    command: >
      sh -c "/app/scripts/wait_for_it.sh localstack:4566 --timeout=30 -- /app/scripts/run_celery_beat.sh"

networks:
  default:
    name: va-notify
    external: true