version: "3"
services:
  test:
    build:
      context: ..
      dockerfile: ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools,test
    image: &notify_image test-notification-api
    volumes: &notify_volumes
      - "../:/app:rw"
    ports:
      - 6011:6011
    depends_on:
      - db
    command: make test

  db:
    condition: 
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    logging:
      driver: "none"
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_PASSWORD=LocalPassword
