version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: &vanotify_dockerfile ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools
    image: &vanotify_image notification_api
    volumes: &vanotify_volumes
      - "../:/app:rw"
    ports: &vanotify_ports
      - 6011:6011
    env_file: &vanotify_env_file
      - .local.env
    depends_on:
      - migrations
      - localstack
    command: ./scripts/run_app.sh

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_PASSWORD=LocalPassword

  migrations:
    build:
      context: ..
    image: *vanotify_image
    env_file: *vanotify_env_file
    volumes: *vanotify_volumes
    depends_on:
      - db
    command: ["bash", "-c", "flask db upgrade"]

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file: *vanotify_env_file
    environment:
      - SERVICES=ec2,iam,lambda,s3,ses,sqs,sts
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=0
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - './localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh'

  celery:
    image: *vanotify_image
    volumes: *vanotify_volumes
    env_file: *vanotify_env_file
    command: >
      sh -c "/app/scripts/wait_for_it.sh localstack:4566 --timeout=30 -- /app/scripts/run_celery.sh"
    depends_on:
      - app
      - localstack
      - mountebank
    healthcheck:
      test: ["CMD", "sh", "-c", "/app/scripts/check_celery.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  mountebank:
    container_name: mountebank
    image: bbyars/mountebank:2.4.0
    volumes:
      - ../scripts/mountebank:/mountebank
    ports:
      - 2525:2525
      - 7005:7005
      - 7006:7006
      - 7007:7007
      - 7008:7008
    command: start --configfile /mountebank/imposters.ejs --allowInjection

  redis:
    image: redis
    ports:
      - "6379:6379"

  datadog:
    image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent
    ports:
      - "127.0.0.1:9126:8126"
    volumes:
      - ./tests/snapshots:/snapshots
    environment:
      - LOG_LEVEL=INFO
      - SNAPSHOT_DIR=/snapshots
      - SNAPSHOT_CI=1
      - DD_POOL_TRACE_CHECK_FAILURES=true
      - DD_DISABLE_ERROR_RESPONSES=true
      - ENABLED_CHECKS=trace_content_length,trace_stall,meta_tracer_version_header,trace_count_header,trace_peer_service,trace_dd_service
      - SNAPSHOT_IGNORED_ATTRS=span_id,trace_id,parent_id,duration,start,metrics.system.pid,metrics.system.process_id,metrics.process_id,meta.runtime-id,meta._dd.p.tid,meta.pathway.hash,metrics._dd.tracer_kr,meta._dd.parent_id