version: "3"
services:
  app:
    profiles: 
      - app
    build:
      context: ..
      dockerfile: &dockerfile ci/Dockerfile.kwm
    image: &notify_image notification_api
    ports: &notify_ports
      - 6011:6011
    command: ./scripts/run_app.sh

  local:
    profiles: 
      - local
    build:
      context: ..
      dockerfile: *dockerfile
      args:
        POETRY_ARGS: --with static_tools
    image: *notify_image
    volumes: &notify_volumes
      - "../:/app:ro"
    ports: *notify_ports
    env_file:
      - .local.env
    depends_on:
      - migrations
      - localstack
    command: ./scripts/run_app.sh

  test:
    profiles:
      - test
    build:
      context: ..
      dockerfile: *dockerfile
      args:
        POETRY_ARGS: --with static_tools,test
    image: *notify_image
    volumes: 
      - "../:/app:rw"
    ports: *notify_ports
    env_file:
      - .local.env
      - ../tests/env_vars
    depends_on:
      - test-db
    command: make test

  db:
    profiles:
      - local
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_PASSWORD=LocalPassword

  test-db:
    profiles:
      - test
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_notification_api
      - POSTGRES_PASSWORD=LocalPassword

  migrations:
    profiles:
      - local
    build:
      context: ..
    image: *notify_image
    env_file:
      - .local.env
    volumes:
      - "../:/app:ro"
    depends_on:
      - db
    command: ["bash", "-c", "flask db upgrade"]

  localstack:
    profiles:
      - local
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file:
      - .local.env
    environment:
      - SERVICES=ec2,iam,lambda,s3,ses,sqs,sts
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=0
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - './localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh'

  celery:
    profiles:
      - local
    image: *notify_image
    volumes: *notify_volumes
    env_file:
      - .local.env
    command: >
      sh -c "/app/scripts/wait_for_it.sh localstack:4566 --timeout=30 -- /app/scripts/run_celery.sh"
    depends_on:
      - local
      - localstack
      - mountebank
    healthcheck:
      test: ["CMD", "sh", "-c", "/app/scripts/check_celery.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  mountebank:
    profiles:
    - local
    container_name: mountebank
    image: bbyars/mountebank:2.4.0
    volumes:
      - ../scripts/mountebank:/mountebank
    ports:
      - 2525:2525
      - 7005:7005
      - 7006:7006
      - 7007:7007
      - 7008:7008
    command: start --configfile /mountebank/imposters.ejs --allowInjection

  redis:
    profiles:
    - local
    image: redis
    ports:
      - "6379:6379"