services:
  app:
    build:
      context: ..
      dockerfile: &vanotify_dockerfile ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools
    image: &vanotify_image notification_api
    volumes: &vanotify_volumes
      - "../:/app:rw"
    ports: &vanotify_ports
      - 6011:6011
    env_file: &vanotify_env_file
      - .local.env
    depends_on:
      - migrations
      - localstack
    command: ./scripts/run_app.sh

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_PASSWORD=LocalPassword

  migrations:
    build:
      context: ..
    image: *vanotify_image
    env_file: *vanotify_env_file
    volumes: *vanotify_volumes
    depends_on:
      - db
    command: ["bash", "-c", "flask db upgrade"]

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    env_file: *vanotify_env_file
    environment:
      - SERVICES=ec2,iam,lambda,s3,ses,sqs,sts
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=0
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - './localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh'

  celery:
    image: *vanotify_image
    volumes: *vanotify_volumes
    env_file: *vanotify_env_file
    command: >
      sh -c "/app/scripts/wait_for_it.sh localstack:4566 --timeout=30 -- /app/scripts/run_celery.sh"
    depends_on:
      - app
      - localstack
      - mountebank
    healthcheck:
      test: ["CMD", "sh", "-c", "/app/scripts/check_celery.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  twilio:
    image: stoplight/prism:4
    ports:
      - '4010:4010'
    command: mock -h 0.0.0.0 https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json
  redis:
    image: redis
    ports:
      - "6379:6379"
