# Elasticsearch and Kibana
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - memory=1g
      - xpack.ml.use_auto_machine_memory_percent=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  comp-pen-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comp-pen-app
    volumes:
      - ./:/app
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - DATE_FIELDS="Date/Time Closed,Date/Time Opened"
    depends_on:
      - elasticsearch