name: Build and Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        default: "dev"
        type: string
      ref:
        required: true
        type: string
    # paths-ignore:
    #   - "user_flows/**.py"
    #   - "lambda_functions/*"
    #   - ".github/workflows/lambda-functions.yaml"

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Configure VAEC AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Login to VAEC ECR
        id: login-ecr-vaec
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          file: ci/Dockerfile
          context: .
          push: true
          tags: ${{ steps.login-ecr-vaec.outputs.registry }}/notification_api:${{ inputs.ref }}_${{ inputs.environment }}
      
      - name: Perform twistlock scan
        if: inputs.environment == "perf"
        uses: ./.github/actions/run-commands-on-ec2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-vaec.outputs.registry }}
          IMAGE_TAG: ${{ steps.set-image-tag.outputs.image-tag }}
        with:
          instance-id-ssm-parameter-path: /utility/twistlock/instance
          commands: >-
            "aws --region us-gov-west-1 ecr get-login-password | docker login --username AWS --password-stdin '"$ECR_REGISTRY"' 2>/dev/null",
            "docker pull '"$ECR_REGISTRY"'/'"$IMAGE_REPOSITORY"':'"$IMAGE_TAG"' 1>/dev/null",
            "docker logout '"$ECR_REGISTRY"'",
            "export TWISTLOCK_PASSWORD=$(aws --region us-gov-west-1 ssm get-parameter --name /utility/twistlock/vanotify-ci-user-password --with-decryption | jq '.Parameter.Value' -r)",
            "twistcli images scan --project VaNotify --address https://twistlock.devops.va.gov --user vanotify-ci-user '"$ECR_REGISTRY"'/'"$IMAGE_REPOSITORY"':'"$IMAGE_TAG"'",
            "STATUS_CODE=$?",
            "docker image prune -a -f 1>/dev/null",
            "exit $STATUS_CODE"
