name: Create And Post Tag with Summary

on: 
  workflow_call:
  push:
    branches:
      - 1727-cd-pipeline-versioning

jobs:
  create-and-post-tag:
    if: ${{ inputs.create-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create and Post Tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/createAndPostTag.js';
            const createAndPostTag = require(path);
            createAndPostTag({github, context, core});

