name: Create And Post Tag with Summary

on: 
  workflow_call:
    outputs:
      previousVersion:
        description: "This value is used for generating release notes from the previous tag"
        value: ${{ jobs.create-and-post-tag.outputs.previousVersion }}

jobs:
  create-and-post-tag:
    runs-on: ubuntu-latest
    outputs:
      previousVersion: ${{ steps.create_tag.outputs.previousVersion }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create and Post Tag
        id: create_tag
        run: echo "previousVersion=1.12.1" >> $GITHUB_OUTPUT

      # - name: Create and Post Tag
        # id: create_tag
        # uses: actions/github-script@v7
        # with:
          # github-token: ${{ secrets.VAR_PAT }}
          # script: |
          # This script outputs previousVersion for create-release-notes.yml
            # const createAndPostTag = require('.github/scripts/createAndPostTag.js');
            # createAndPostTag({github, context, core});

