name: Create And Post Tag with Summary

on: 
  workflow_call:
    outputs:
      previous_version:
        description: "Will be used for generating release notes from the previous tag"
        value: ${{ jobs.create-and-post-tag.outputs.previous_version }}

jobs:
  create-and-post-tag:
    runs-on: ubuntu-latest
    outputs:
      previous_version: ${{ steps.create_tag.outputs.previous_version }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create and Post Tag
        id: create_tag
        run: echo "previous_version=1.12.0" >> $GITHUB_OUTPUT

      - name: Create and Post Tag
        id: create_tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/createAndPostTag.js';
            const createAndPostTag = require(path);
            createAndPostTag({github, context, core});

