name: Create Release Notes

on: 
  workflow_call:

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create and Post Tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/createReleaseNotes.js';
            const createReleaseNotes = require(path);
            createReleaseNotes({github, context, core});

