# .github/workflows/deploy-release.yml
# This workflow should only be run when a release or prerelease need to be deployed outside the cd-pipeline.yml
# dev_deploy.yml only deploys hashes - this workflow ensures the tag is deployed
# this ensures the tag name shows up correctly in Datadog for deployment tracking
name: Deploy API Release
run-name: "Deploy Release to ${{ inputs.environment }}"

on:
  push:
    branches:
      - 1721-tagfix-triggerdelete-updatenotes

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        default: dev
        options:
          - dev
          - perf
          - staging
          - prod
      ref:
        description: "Branch or Commit"
        default: master
        required: true
        type: string
      lambdaDeploy:
        description: "Include Lambda in deployment?"
        default: false
        required: false
        type: boolean

env:
  TAG: ${{ github.event.inputs.ref || '1.7.10' }}
  ENV: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  setup-environment:
    name: "setup-env-${{ env.ENV }}"
    runs-on: ubuntu-latest
    environment: ${{ env.ENV }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}

      - name: Env Values
        run: |
          echo "The environment is ${{ env.ENV }}"
          echo "The branch/tag is ${{ env.TAG }}"

  run-build:
    needs: [setup-environment]
    uses: ./.github/workflows/build.yml
    with:
      environment: "${{ env.ENV }}"
      ref: "${{ env.TAG }}"
    secrets: inherit

  run-lambda-deploy:
    if: ${{ github.event.inputs.lambdaDeploy }}
    needs: [setup-environment]
    uses: ./.github/workflows/lambda-functions.yml
    with:
      environment: "${{ env.ENV }}"
      ref: "${{ env.TAG }}"
      lambdaName: "All"
    secrets: inherit

  run-deployment:
    needs: [setup-environment, run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "${{ env.ENV }}"
      ref: "${{ env.TAG }}"
    secrets: inherit

  run-qa-suite:
    needs: [run-deployment]
    uses: ./.github/workflows/run-regression.yml
    with:
      environment: "${{ env.ENV }}"
    secrets: inherit

