name: CD Pipeline PR Labels and Semver bump Summary

on: 
  workflow_call:
  push: 
    branches:
      - 1727-HOTFIX

jobs:
  # check-pr-sem:
    # runs-on: ubuntu-latest
    # permissions:
      # contents: write
    # steps:
      # - uses: actions/checkout@v4
      # - name: PR Label Semver
        # uses: actions/github-script@v7
        # with:
          # github-token: ${{ secrets.VAR_PAT }}
          # script: |
            # const path = '.github/scripts/prLabelSemver.js';
            # const prLabelSemver = require(path);
            # prLabelSemver({github, context, core});

  test-merge-workflow-to-a-branch:
    # These permissions are needed to write to the release branch
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          # ref: release
          ref: 1727-hotfix-pat-test
          fetch-depth: 0
          # Fine-grained PAT with contents:write and workflows:write
          # scopes
          token: ${{ secrets.CD_PAT }}

