name: Run regression tests

on:
  workflow_call:
    inputs:
      environment:
        description: "Notification-api deployment environment to test (dev|perf|staging)"
        default: "perf"
        required: true
        type: string
      qa-image-branch:
        description: "Will run latest SHA from branch"
        default: "master"
        required: true
        type: string

jobs:
  pull-and-run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.qa-image-branch }}

      - name: Configure VAEC AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Login to VAEC ECR
        id: login-ecr-vaec
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: QA regression test - public endpoints
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-vaec.outputs.registry }}
        run: |
          # Add user qa-container with UID 1051 and home directory at /home/qa-container
          sudo useradd -u 1051 -m -d /home/qa-container -s /bin/bash qa-container

          ## Set the working directory to /home/qa-container
          #cd /home/qa-container

          ## Copy the contents of the host's build context directory to /home/qa-container
          ##sudo cp -R . /home/qa-container

          #aws ssm get-parameter --name /notification-api-qa/env --with-decryption | jq '.Parameter.Value' -r > .env

          ## Change the ownership of all files and directories in /home/qa-container to qa-container:qa-container
          #sudo chown -R qa-container:qa-container /home/qa-container
          ##sudo chown 1051:1051 .env

          ##sudo chgrp qa-container .env
          #chmod 640 .env

          #ls -al
          #pwd

          ##aws --region us-gov-west-1 ecr get-login-password | docker login --username AWS --password-stdin "$ECR_REGISTRY" 2>/dev/null

          ##docker pull ${{ env.ECR_REGISTRY }}/notification_api_qa:master 1>/dev/null

          ##docker logout '$ECR_REGISTRY'

          ##docker run --rm --name qa_container \
          ##-v $(pwd)/.env:/home/qa-container/.env \
          ##"$ECR_REGISTRY/notification_api_qa:master" \
          ###pytest -ra -v tests/ --platform local \
          ##pytest -ra -v tests/test_organizations.py --platform local \
          ##--environment '${{ inputs.environment }}'

          ##docker image prune -a -f 1>/dev/null
