name: Release Trigger
on:
  release:
    types: [prereleased, published, released]

jobs:
  setup-release:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.tag.outputs.version }}
      env: ${{ steps.setup.outputs.environment }}
    steps:
      - name: Check release
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Is pre-release (boolean): ${{ github.event.release.prerelease }}"
          echo "Is release (string): ${{ github.event.action }}"
      - name: Setup Environment
        id: setup
        uses: actions/github-script@v6
        with:
          script: |
            if (github.event.release.isPrerelease) {
              core.setOutput('environment', 'staging')
            }
            if ('${{ github.event.action }}' === 'released') {
              core.setOutput('environment', 'prod')
            }

      - name: Get the version
        id: tag
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Env Values
        run: |
          echo "The environment is ${{ steps.setup.outputs.environment }}"
          echo "The tag is ${{ steps.tag.outputs.version }}"

  run-build:
    needs: [setup-release]
    uses: ./.github/workflows/build.yml
    with:
      environment: "${{ needs.setup-release.outputs.env }}"
      ref: "${{ needs.setup-release.outputs.git-tag }}"
    secrets: inherit

  run-lambda-deploy:
    needs: [setup-release]
    uses: ./.github/workflows/lambda-functions.yml
    with:
      environment: "${{ needs.setup-release.outputs.env }}"
      ref: "${{ needs.setup-release.outputs.git-tag }}"
      lambdaName: "All"
    secrets: inherit

  run-deployment:
    needs: [setup-release, run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "${{ needs.setup-release.outputs.env }}"
      ref: "${{ needs.setup-release.outputs.git-tag }}"
    secrets: inherit
