name: Call Notification API QA Regression Tests

on: 
  workflow_call:
    inputs:
      environment:
        description: 'Notification-api deployment environment to test (dev|perf|staging)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Notification-api deployment environment to test (dev|perf|staging)'
        required: true
        type: string

jobs:
  trigger-regression-tests:
    name: "Run regression for ${{ inputs.environment }}"
    runs-on: ubuntu-latest  # specify the runner
    name: Trigger Regression Tests
    steps:
    - uses: actions/checkout@v4

    - name: Trigger Regression Workflow
      uses: actions/github-script@v6
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      with:
        github-token: ${{ secrets.DISPATCH_PAT }}
        script: |
          const path = '.github/scripts/trigger-regression.js';
          const triggerAndWait = require(path);
          triggerAndWait({github, context, core});

