name: Semantic Versioning

on: 
  push:
    branches:
      - 1727-cd-pipeline-versioning
  workflow_call:
    inputs:
      create-tag:
        type: boolean
        default: false

jobs:
  summary_for_qa:
    if: ${{ !inputs.create-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Post QA Summary
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/postQA.js';
            const { generatePRSummary } = require(path);
            generatePRSummary({github, context, core});

  # It's likely best that this script output the value of the semver bump, 
  # which is then used in the subsequent step to update the var.RELEASE_VERSION
  create_and_post_tag:
    # if: ${{ inputs.create-tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and Post Tag
        uses: actions/github-script@v7
        with:
          script: |
            const path = '.github/scripts/createAndPushTag.js';
            const { createAndPushTag } = require(path);
            createAndPushTag({github, context, core});

  # update_RELEASE_VERSION_repo_value:
    # depends_on: ${{ create_and_post_tag }}

