# .github/workflows/semver.yml
name: Semantic Versioning

on:
  pull_request:
    branches:
      - 1727-cd-pipeline-versioning
    types: [closed, opened, labeled, edited, reopened]
  issues:
    types:
      - labeled
      - closed 
  push: 
    branches:
      - 1727-cd-pipeline-versioning
      - 1727-test

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  print-pr-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Print out PR labels
      uses: actions/github-script@v7
      with:
        script: |
          const path = '.github/scripts/pr-label-versioning.js';
          const prData = require(path);
          prData({github, context, core});

  # Test cause this is the current roadmapped next step
  approval-to-deploy:
    needs: print-pr-labels
    environment: 
      name: perf-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pause for manual approval
        run: |
          echo "Deploying commit SHA ${{ github.sha }}, the latest merge to master"
          echo "Deployment paused for manual approval."

