name: Semantic Versioning

on: 
  push:
    branches:
      - 1727-cd-pipeline-versioning
  workflow_call:
    inputs:
      create-tag:
        type: boolean
        default: false

jobs:
  summary_for_qa:
    if: ${{ !inputs.create-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Post QA Summary
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.VAR_PAT }}
          script: |
            const path = '.github/scripts/postQA.js';
            const { generatePRSummary } = require(path);
            generatePRSummary({github, context, core});

  create_and_post_tag:
    # if: ${{ inputs.create-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.new_version.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - name: Create and Post Tag
        id: new_version
        run: |
          echo "NEW_VERSION=2.2.2-test" >> "$GITHUB_OUTPUT"

      - name: Echo and update the RELEASE_VERSION
        env:
          GH_TOKEN: ${{ secrets.VAR_PAT }}
          NEW_VERSION: ${{ steps.new_version.outputs.NEW_VERSION }}
          RELEASE_VERSION: ${{ vars.RELEASE_VERSION }}
        run: |
          echo "Previous RELEASE_VERSION repo variable was $RELEASE_VERSION" | tee -a $GITHUB_STEP_SUMMARY
          # gh variable set RELEASE_VERSION --body "$NEW_VERSION"
          gh variable set RELEASE_VERSION --body "555"
          echo "Updated RELEASE_VERSION is $RELEASE_VERSION" | tee -a $GITHUB_STEP_SUMMARY
          sleep 5

  update-release-version-variable:
    needs: create_and_post_tag
    runs-on: ubuntu-latest
    steps:
      - name: Updated Value for RELEASE_VERSION
        env:
          RELEASE_VERSION: ${{ vars.RELEASE_VERSION }}
        run: |
          echo "Updated RELEASE_VERSION variable is $RELEASE_VERSION" | tee -a $GITHUB_STEP_SUMMARY

        # get this to output the new_version value
        # uses: actions/github-script@v7
        # with:
          # github-token: ${{ secrets.VAR_PAT }}
          # script: |
            # const path = '.github/scripts/createAndPushTag.js';
            # const { createAndPushTag } = require(path);
            # createAndPushTag({github, context, core});
