name: Semantic Versioning

on: 
  pull_request:
    branches:
      - 1727-cd-pipeline-versioning
    types: [closed, opened, labeled, edited, reopened]
  issues:
    types: [labeled, closed]
  workflow_call:
    inputs:
      create-tag:
        type: boolean
        default: false

jobs:
  summary_for_qa:
    if: ${{ !inputs.create-tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Post QA Summary
        uses: actions/github-script@v7
        with:
          script: |
            const path = '.github/scripts/postQA.js';
            const { generatePRSummary } = require(path);
            generatePRSummary({github, context, core});

  create_and_post_tag:
    # if: ${{ inputs.create-tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and Post Tag
        uses: actions/github-script@v7
        with:
          script: |
            const path = '.github/scripts/createAndPushTag.js';
            const { createAndPushTag } = require(path);
            createAndPushTag({github, context, core});

