name: Semantic Versioning

on: 
  workflow_call:
    inputs:
      create-tag:
        type: boolean
        default: false
    outputs:
      version: ${{ jobs.create-version-bump-string.outputs.version }}

jobs:
  create-version-bump-string:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_output.outputs.new_version }}

    steps:

    - uses: actions/checkout@v4

    - name: create a version string
      id: version_output
      uses: actions/github-script@v7
      with:
        script: |
          const path = '.github/scripts/pr-label-versioning.js';
          const prData = require(path);
          prData({github, context, core});

