name: Tag push to Perf
on: 
  push:
    tags:
      - 'v*'
  
jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs: 
      git-tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Check Tag
        run: echo ${{steps.tag.outputs.tag}}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  run-build:
    needs: [setup-environment]
    uses: ./github/workflows/build.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit
  
  run-twistlock:
    needs: [setup-environment, run-build]
    if: ${{ github.event.inputs.environment }} == "dev" || ${{ github.event.inputs.environment }} == "perf"
    uses: ./github/workflows/twistlock.yml
    with:
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit

  run-deployment:
    needs: [setup-environment, run-build, run-twistlock]
    uses: ./github/workflows/deployment.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit
  
  run-lambda-deploy:
    needs: [setup-environment]
    uses: ./github/workflows/lambda-functions.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit

  run-user-flows:
    if: ${{ github.event.inputs.environment }} == "dev" || ${{ github.event.inputs.environment }} == "perf"
    needs: [run-deployment, run-lambda-deploy]
    uses: ./github/workflows/user_flows.yml
    with:
      environment: "perf"
    secrets: inherit
