name: Test workflow

on:
  workflow_run:
    workflows: 
      - Development CI
      - dev-ci.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ toJson(github.event) }}