name: Test workflow_run

on:
  workflow_run:
    workflows: ["Development CI"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ toJson(github.event) }}